[project]
name = "association-rules-mining"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "metatrader5>=5.0.5430",
    "mlxtend>=0.23.4",
    "pyyaml>=6.0.3",
    "ta-lib>=0.6.8",
]
